planning_plugins: pce_ros/PCEPlannerManager

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

pce:
  planning_groups:
    - manipulator
    - arm
    - panda_arm
  
  panda_arm:
    pce_planner:
      num_samples: 3000
      num_iterations: 20
      eta: 0.99
      temperature: 2.0
      convergence_threshold: 0.0001
      num_discretization: 20
      total_time: 5.0
      node_collision_radius: 0.20

    collision_clearance: 0.15
    collision_threshold: 0.15